spring:
  banner:
    location: classpath:banner.txt

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  profiles:
    active: dev

server:
  port: 8080




